### ISSUE TITLE
Feature Request - Support for playlists

### ISSUE THREAD

**Issue by dp0s** [CliffracerMerchant/SoundAura#41]
Hello, thanks for this app. I particularly like that I can play music alongside in the background while watching videos. Couldn't find any other player to support this.

The one thing I still need - instead of adding a single file, I would like to add a playlist of songs to play consecutively. Imported from m3u file or from Android's already existing playlists. Shouldn't be hard to implement?

**Comment by CliffracerMerchant** [comment]
I know this isn't an ideal solution, but if I wanted a playlist like functionality I would just use some sort of audio joiner app to join the playlist into one audio file. Obviously this method would take up a bit more space, but unless you're dealing with lossless audio or extremely long audio files it shouldn't be too big of a deal with modern storage sizes.

The reason I'm hesitant to add this feature to the app is that it uses SAF to get permission for specific files, and I'm not sure how this would work with playlists. I think the user would have to manually give permission to read the playlist file and all of the audio files that are in it, instead of just being able to add the playlist alone. I'm also a little busy at the moment, so if I were going to add this it probably wouldn't be for a few weeks at least.

**Comment by dp0s** [comment]
Joining audio is a good work around, but seems like too much effort in the long term. I would also like the option to play the tracks in random order if possible.

Regarding SAF: it might be enough to pick the playlist file via SAF. To access the music, there is an permission  "Allow access to media", which is used by Vanilla Music Player e.g.

Btw, this is not urgent at all, I can wait as long as it takes. I'm glad you are publishing this as free software :)

**Comment by CliffracerMerchant** [comment]
Alright, I'll look into it when I get a chance.

**Comment by CliffracerMerchant** [comment]
Sorry this ended up taking so long to finish, but I did add it as part of the 1.5.0 update. I'm not sure why but this issue didn't get closed automatically for some reason. I wasn't able to get the importing of playlist files working, so you'll have to select all of the files you want as part of the playlist in the system file picker that appears when you tap the add button. The 1.5.0 update is still working it's way through F-droid, but you can download the apk directly on the [v1.5.0 release page](https://github.com/CliffracerMerchant/SoundAura/releases/tag/v1.5.0) if you want.
